language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"


service:
  - postgresql

before_install:
  - export APP_SETTINGS="project.server.config.TestingConfig"
  - export SECRET_KEY="justatest"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python manage.py cov

after_success:
  coveralls
